---
app_user: "{{ app_user_vault }}"
app_group: "{{ app_user_vault }}"

app_path: "$HOME/Workspace/07-local/app"
app_network: local_network

# Applications disponibles
deploy_excalidraw: true
deploy_open_webui: true
